spring:
  datasource:
    url: jdbc:mysql://localhost:3306/finance_tracker?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: baizhihao
    driver-class-name: com.mysql.cj.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapper/*.xml
    configuration:
      map-underscore-to-camel-case: true
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

server:
  port: 8080


jwt:
  secret: finance-tracker-jwt-secret-key-2026-zhihao
  expiration: 86400000
